modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "kupe"
version = "${version}"
displayName = "Kupe GUI"
authors = "Valoeghese"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.kupe]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kupe]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
