modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "kupe_test"
version = "${version}"
displayName = "Kupe Testmod"
authors = "Valoeghese"
description = '''
Test the Kupe GUI library
'''
#logoFile = ""

[[dependencies.kupe_test]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kupe_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kupe_test]]
modId = "kupe"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

